[project]
name = "options-tboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "comtypes>=1.4.16",
    "ipykernel>=7.3.0",
    "kgisuperpy>=2.1.1",
    "pydantic-ai>=2.40.0",
    "pyqt5<5.15.11",
    "pyqt5-qt5<5.15.11",
    "python-dotenv>=1.2.3",
    "pywin32>=312",
    "requests>=2.34.2",
]
