[project]
name = "options-tboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ib-async>=2.1.0",
    "ipykernel>=7.3.0",
    "nicegui>=2.0.0",
    "pip>=26.2.1",
    "pydantic-ai>=2.40.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "setuptools>=84.0.0",
    "thetadata>=1.0.10",
    "yfinance>=1.7.0",
]
